import { afterEach, describe, expect, it } from 'vitest';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { buildApp, type BuiltApp } from '../src/app.js';
import type { Mailer } from '../src/infrastructure/mail.js';
import { LocalStorageProvider } from '../src/infrastructure/storage/index.js';

class CaptureMailer implements Mailer { code=''; async sendOtp(_email:string,code:string):Promise<void>{this.code=code} }
class RejectingMailer implements Mailer { calls=0; async sendOtp():Promise<void>{this.calls++;throw new Error('SMTP unavailable')} }
const cleanup:Array<()=>Promise<void>>=[];afterEach(async()=>{while(cleanup.length)await cleanup.pop()!()});
async function fixture():Promise<{built:BuiltApp;mailer:CaptureMailer;cookie:string;root:string}>{const root=await mkdtemp(join(tmpdir(),'big-upload-api-'));const mailer=new CaptureMailer();const built=await buildApp({mailer,config:{databaseUrl:`file:${join(root,'test.db')}`,localStoragePath:join(root,'storage'),publicOrigin:'http://localhost:3000',logLevel:'silent'}});cleanup.push(async()=>{await built.close();await rm(root,{recursive:true,force:true})});const requested=await built.app.inject({method:'POST',url:'/api/auth/otp/request',payload:{email:'person@example.com'}});expect(requested.statusCode).toBe(202);const challenge=requested.json<{challengeId:string}>();const verified=await built.app.inject({method:'POST',url:'/api/auth/otp/verify',payload:{challengeId:challenge.challengeId,code:mailer.code}});expect(verified.statusCode).toBe(200);const setCookie=verified.headers['set-cookie'];const cookie=Array.isArray(setCookie)?setCookie[0]!:setCookie!;return{built,mailer,cookie:cookie.split(';')[0]!,root}}

describe('API main flow',()=>{
  it('allows WebAssembly hashing without enabling general script eval',async()=>{const root=await mkdtemp(join(tmpdir(),'big-upload-api-'));const built=await buildApp({config:{databaseUrl:`file:${join(root,'test.db')}`,localStoragePath:join(root,'storage'),publicOrigin:'http://localhost:3000',logLevel:'silent'}});cleanup.push(async()=>{await built.close();await rm(root,{recursive:true,force:true})});const response=await built.app.inject({method:'GET',url:'/health/live'});const policy=String(response.headers['content-security-policy']);expect(policy).toContain("script-src 'self' 'wasm-unsafe-eval'");expect(policy.split(/\s|;/)).not.toContain("'unsafe-eval'")});
  it('permits direct browser connections to the configured R2 origin only',async()=>{const root=await mkdtemp(join(tmpdir(),'big-upload-api-'));const built=await buildApp({storage:new LocalStorageProvider(join(root,'storage'),'http://localhost:3000','test-signing-secret'),config:{databaseUrl:`file:${join(root,'test.db')}`,storageDriver:'r2',r2Endpoint:'https://account-id.r2.cloudflarestorage.com/api',r2Bucket:'uploads',r2AccessKeyId:'key',r2SecretAccessKey:'secret',logLevel:'silent'}});cleanup.push(async()=>{await built.close();await rm(root,{recursive:true,force:true})});const response=await built.app.inject({method:'GET',url:'/health/live'});const policy=String(response.headers['content-security-policy']);expect(policy).toContain("connect-src 'self' https://account-id.r2.cloudflarestorage.com");expect(policy).not.toContain('https://account-id.r2.cloudflarestorage.com/api')});
  it('exposes the configured file-size limit to authenticated clients',async()=>{const{built,cookie}=await fixture();const response=await built.app.inject({method:'GET',url:'/api/config',headers:{cookie}});expect(response.statusCode).toBe(200);expect(response.json()).toEqual({maxFileSizeBytes:5368709120});expect((await built.app.inject({method:'GET',url:'/api/config'})).statusCode).toBe(401)});
  it('authenticates, uploads a signed local part, completes, previews text and deletes',async()=>{const{built,cookie}=await fixture();const content=Buffer.from('hello world');const prepared=await built.app.inject({method:'POST',url:'/api/uploads/prepare',headers:{cookie},payload:{name:'hello.txt',size:content.length,lastModified:1,declaredMime:'text/plain',quickFingerprint:'fingerprint-123'}});expect(prepared.statusCode).toBe(200);const upload=prepared.json<{upload:{id:string;partSize:number}}>().upload;const presigned=await built.app.inject({method:'POST',url:`/api/uploads/${upload.id}/presign`,headers:{cookie},payload:{partNumbers:[1]}});expect(presigned.statusCode).toBe(200);const signed=new URL(presigned.json<{parts:Array<{url:string}>}>().parts[0]!.url);const put=await built.app.inject({method:'PUT',url:signed.pathname+signed.search,headers:{'content-type':'application/octet-stream'},payload:content});expect(put.statusCode).toBe(200);const etag=String(put.headers.etag).replaceAll('"','');const ack=await built.app.inject({method:'POST',url:`/api/uploads/${upload.id}/parts/ack`,headers:{cookie},payload:{parts:[{partNumber:1,etag,size:content.length}]}});expect(ack.statusCode).toBe(200);const completed=await built.app.inject({method:'POST',url:`/api/uploads/${upload.id}/complete`,headers:{cookie}});expect(completed.statusCode).toBe(200);const fileId=completed.json<{file:{id:string;detectedMime:string}}>().file.id;expect(completed.json().file.detectedMime).toBe('text/plain');const preview=await built.app.inject({method:'GET',url:`/api/files/${fileId}/preview`,headers:{cookie,range:'bytes=0-4'}});expect(preview.statusCode,preview.body).toBe(206);expect(preview.body).toBe('hello');expect(preview.headers['content-range']).toBe('bytes 0-4/11');expect(preview.headers['content-type']).toContain('text/plain');const detail=await built.app.inject({method:'GET',url:`/api/files/${fileId}`,headers:{cookie}});const signedPreview=new URL(detail.json<{previewUrl:string}>().previewUrl);const signedRange=await built.app.inject({method:'GET',url:signedPreview.pathname+signedPreview.search,headers:{range:'bytes=6-10'}});expect(signedRange.statusCode).toBe(206);expect(signedRange.body).toBe('world');expect(signedRange.headers['content-range']).toBe('bytes 6-10/11');const download=await built.app.inject({method:'GET',url:`/api/files/${fileId}/download`,headers:{cookie}});expect(download.statusCode).toBe(200);expect(download.headers['content-disposition']).toContain('attachment');const text=await built.app.inject({method:'GET',url:`/api/files/${fileId}/text`,headers:{cookie}});expect(text.json()).toEqual({content:'hello world'});const list=await built.app.inject({method:'GET',url:'/api/files',headers:{cookie}});expect(list.json().files).toHaveLength(1);const deleted=await built.app.inject({method:'DELETE',url:`/api/files/${fileId}`,headers:{cookie}});expect(deleted.statusCode).toBe(204)});
  it('enforces server-side OTP cooldown and resumes an existing upload',async()=>{const{built,cookie}=await fixture();const second=await built.app.inject({method:'POST',url:'/api/auth/otp/request',payload:{email:'person@example.com'}});expect(second.statusCode).toBe(429);expect(second.json().error.code).toBe('OTP_RESEND_COOLDOWN');const payload={name:'resume.txt',size:8,lastModified:9,declaredMime:'text/plain',quickFingerprint:'fingerprint-resume'};const first=await built.app.inject({method:'POST',url:'/api/uploads/prepare',headers:{cookie},payload});expect(first.statusCode).toBe(200);const firstId=first.json().upload.id;const resumed=await built.app.inject({method:'POST',url:'/api/uploads/prepare',headers:{cookie},payload});expect(resumed.statusCode).toBe(200);expect(resumed.json().upload.id).toBe(firstId);expect(resumed.json().resumed).toBe(true);const active=await built.app.inject({method:'GET',url:'/api/uploads?state=active',headers:{cookie}});expect(active.statusCode).toBe(200);expect(active.json().uploads).toHaveLength(1);expect(active.json().uploads[0]).not.toHaveProperty('storageUploadId');});
  it('clears the OTP cooldown when SMTP delivery fails',async()=>{const root=await mkdtemp(join(tmpdir(),'big-upload-api-'));const mailer=new RejectingMailer();const built=await buildApp({mailer,config:{databaseUrl:`file:${join(root,'test.db')}`,localStoragePath:join(root,'storage'),publicOrigin:'http://localhost:3000',logLevel:'silent'}});cleanup.push(async()=>{await built.close();await rm(root,{recursive:true,force:true})});const request={method:'POST' as const,url:'/api/auth/otp/request',payload:{email:'person@example.com'}};const first=await built.app.inject(request);expect(first.statusCode).toBe(500);expect(first.json()).not.toHaveProperty('challengeId');expect((await built.app.inject(request)).statusCode).toBe(500);expect(mailer.calls).toBe(2)});
  it('rejects unauthenticated control-plane access and spoofed binary text',async()=>{const{built,cookie}=await fixture();expect((await built.app.inject({method:'GET',url:'/api/files'})).statusCode).toBe(401);const data=Buffer.from([0,1,2,3]);const prepared=await built.app.inject({method:'POST',url:'/api/uploads/prepare',headers:{cookie},payload:{name:'fake.txt',size:data.length,lastModified:1,declaredMime:'text/plain',quickFingerprint:'fingerprint-456'}});const id=prepared.json().upload.id;const signed=new URL((await built.app.inject({method:'POST',url:`/api/uploads/${id}/presign`,headers:{cookie},payload:{partNumbers:[1]}})).json().parts[0].url);const put=await built.app.inject({method:'PUT',url:signed.pathname+signed.search,headers:{'content-type':'application/octet-stream'},payload:data});const etag=String(put.headers.etag).replaceAll('"','');await built.app.inject({method:'POST',url:`/api/uploads/${id}/ack`,headers:{cookie},payload:{parts:[{partNumber:1,etag,size:data.length}]}});expect((await built.app.inject({method:'POST',url:`/api/uploads/${id}/complete`,headers:{cookie}})).statusCode).toBe(415)});
});
